name: Run Python Server with Ngrok

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update && \
        sudo apt install zip brotli python3 python3-aiohttp file xz-utils ngrok -y

    - name: Start Python Server
      run: |
        python3 your_script.py &

    - name: Start Ngrok
      run: ngrok http 1337 > ngrok.log & sleep 5

    - name: Display Ngrok URL
      run: |
        grep -o 'https://[0-9a-z]*\.ngrok\.io' ngrok.log
